use charming;
drop table if exists reporting;
create table reporting(transaction_id int(10) unsigned,
				       sales_module_transaction_id int(10) unsigned,
					   transaction_source smallint(5) unsigned,
					   tender_type	char(4),
					   store_no	smallint(5) unsigned,
					   customer_id	int(5) unsigned,
					   sales_associate_no int(10) unsigned,
					   transaction_type	smallint(5) unsigned,
					   promotion_id	smallint(5) unsigned,
					   transaction_date	date,
					   pos_transaction_no int(10) unsigned,
					   register_no	smallint(5) unsigned,
					   segmentation_flag_a smallint(5) unsigned,
					   segmentation_flag_b	smallint(5) unsigned,
					   segmentation_flag_c	smallint(5) unsigned,
					   segmentation_flag_d	smallint(5) unsigned,
					   segmentation_flag_e	smallint(5) unsigned,
					   segmentation_flag_f	smallint(5) unsigned,
					   segmentation_flag_g	smallint(5) unsigned,
					   segmentation_flag_h	smallint(5) unsigned,
					   customer_no_flag	smallint(5) unsigned,
					   total_net_retail	decimal(7,2),
					   no_transaction_lines	smallint(5) unsigned,
					   reward_points_flag tinyint(1) unsigned,
					   total_net_retail_central	decimal(7,2),
					   exchange_rate decimal(7,2),
					   currency_code char(3),
					   posted_date	datetime,
					   transaction_time	datetime) engine = MyISAM;
