use charming;
drop table if exists reporting_promo;
create table reporting_promo(promotion_id	int(5) unsigned,
							 promotion_description varchar(128),
							 promotion_short_description varchar(64),
							 status	smallint(5) unsigned,
							 targeted_customer_flag	smallint(5) unsigned,
							 promoted_coupon_flag	smallint(5) unsigned,
							 promoted_class_flag	smallint(5) unsigned,
							 promoted_style_flag	smallint(5) unsigned,
							 promoted_vendor_flag	smallint(5) unsigned,
							 promoted_store_flag	smallint(5) unsigned,
							 promotion_weight	smallint(5) unsigned,
							 start_date	date,
							 end_date	date,
							 list_history_flag	smallint(5) unsigned,
							 coupon_history_flag	smallint(5) unsigned,
							 style_history_flag	smallint(5) unsigned,
							 store_history_flag	smallint(5) unsigned,
							 tender_history_flag	smallint(5) unsigned,
							 date_history_flag	smallint(5) unsigned,
							 next_sequence_no	smallint(5) unsigned,
							 last_analysis_date	datetime,
							 date_last_modified	datetime,
							 household_level_flag smallint(5) unsigned,
							 timestamp timestamp) engine = MyISAM;
